# Generated by Django 3.1.1 on 2026-04-27 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_qrattendancelog_qrattendancesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrattendancelog',
            name='scan_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrattendancelog',
            name='scan_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrattendancesession',
            name='attendance_date',
            field=models.DateField(default=datetime.date(2026, 4, 27), help_text='The date attendance is being taken for'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrattendancesession',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrattendancesession',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
